---
title: "Conclusion"
output:
  html_document:
    toc: true
    toc_float: true
---
### Conclusion

```{r, include=FALSE}
#Just copied and pasted from the report discussion.
```

We combined and merged multiple variables into our final dataset. These variables are prcp_ctg(categorized), snow_ctg, season, hour of the day. These graphs show us that there is a slight increase in mean response time when precipitation is heavy; there is an increase in mean response time when snowy condition presented. When analyzing with the season variables, mean response time is slightly increased in winter, which may be explained along with snow variable. On the other hand, when analyzing the effect of the hour of the day on mean response time, It seems that response is delayed peak around 5 am and getting improved. Based on this result, hour of the day will be categorized into dawn, morning, afternoon and night later in our statistical model analysis. 

As we first tried the linear regression we found out that despite the significant p value, the estimate of the variables are very small. We wanted to change to another statistical method to get relatively meaningful result. We summarize the continuous response time in to binary outcomes, about whether it is higher than 8 mins or not. We also categorized the snow and prcp into binary variables. The model we chose is here: 
$$
\begin{aligned}
&logit(P(response\space time > 8 min))\\
&= \beta_{0} + \beta_{1}I(season = Fall) + \beta_{2}I(season = Summer) + \beta_{3}I(season = Winter) \\
& + \beta_{4}I(hour\space of \space day = afternoon) + \beta_{5}I(hour\space of \space day = dawn) + \beta_{6}I(hour\space of \space day = morning) \\
& + \beta_{7}I(snow = 50mm+) + \beta_{8}I(snow = 50mm-) + \beta_{9}I(prcp = 25mm+) + \beta_{10}I(prcp = 25mm-) 
\end{aligned}
$$
In the Odd Ratio table generated frm the code in the above section, we found out that as expected from EDA, compared to no snow conditions, odds of over 8min response time is increased 24% by 0~50mm snow and 47% by over 50mm snow. In summary of the effect of seasons, compared to Spring, Summer does not affect odds of over 8min response time but odds is increased in Fall by 6% and in Winter by 7%. For the rainy condition, statistically significant result was not obtained from prcp variable and it matches the result of EDA. Furthermore, in reference to night, odds of over 8min response time is increased at dawn by 26%, in the morning by 37% and in the afternoon by 35%. It seems like the emergency service in our city is more or less affected by snowy condition, and somewhat delayed in the morning. Further research can be planned to investigate the causation of that, but there is something important to keep in mind that: the avarage response time is pretty small, and most the of recorded response times are lower than 8 minutes. Thus so far we do not need to worry about the medical emergency service provided in our city. 

On the other hand, we have construct logistic analysis on our subset filtered with neighborhood area variables, UMS, and Washington Heights in specific. On Upper West Side, high precipitation is associated with lower odds of response times greater than 8 minutes. What’s interesting here is why? Street closure is associated with the outcome but not statistically significant. Washington Heights, on the other hand, saw afternoon and dawn time, compared to the night time as reference, as contributing factors to the response time greater than 8 minutes with ORs 1.6 and 1.3, respectively. Again street closure is not predictive of the outcome. The null result from street closure could be due to either linking street closure to the zip code in this case is too broad or street closure did not really play a role in our response time. PS. We also fitted the model with neighborhood as predictor variable and found that Washington Heights had 1.05 times the odds of response time greater than 8 minutes compared to the Upper West Side. However the observed effect is not statistically significant. At least we can be rest assured whether where we live, we still receive equal treatment from the emergency dispatcher.

### Screencast
** insert screencast **


