---
title: "Visualisations for EMS Response Time as a function of different predictors"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(maps)
library(mapdata)
library(viridis)
library(ggthemes)
library(lubridate)
library(patchwork)
library(kableExtra)
library(magick)
library(jpeg)
library(grid)

```

Here we showcase a dhasboard of the various plots that led us to come up with the analysis.

```{r data_import_tidying, echo = FALSE}
load('data/finaldat.RData')
load("data/incident_zip_coor.RData")

finaldat = 
  finaldat %>%
  mutate(season = 
           ifelse(incident_month %in% 9:11, "Fall",
           ifelse(incident_month %in% c(12,1,2), "Winter",
           ifelse(incident_month %in% 3:5, "Spring", "Summer"))), 
         hour_of_day = 
           ifelse(hour %in% 6:11, "morning",
           ifelse(hour %in% 12:17, "afternoon",
           ifelse(hour %in% 18:23, "night","dawn"))), 
         over_8min = ifelse(response_time > 8, "8min+", "8min-"),
         prcp_ctg = 
           if_else(prcp == 0, "no_prcp",
           if_else((prcp > 0 & prcp <= 25), "low", "high")),
         snow_ctg = 
           if_else(snow == 0, "no_snow",
           if_else((snow > 0 & snow <= 50), "low", "high")),
         over_8min = fct_relevel(over_8min, "8min-")) 

ny = map_data("county", "new york")

ny_1 = 
  ny %>% 
  filter(subregion %in% c("kings", "bronx", "richmond", "new york", "queens"))

incident_zip_coor = 
  incident_zip_coor %>%
  group_by(zip_code) %>% 
  mutate(response_time = as.numeric(response_time)) %>%
  mutate(mean_res_time = mean(response_time))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Variation of Mean Response Time over different hours of days through the year, per season

```{r}
hour_eda =
  finaldat %>%
  group_by(hour, season) %>% 
  ggplot(aes(x = hour, y = response_time, color = season)) + 
  geom_smooth(se = FALSE) +
  scale_x_continuous(breaks = c(6, 12, 18),
                     labels = c("6am", "12pm", "18pm")) +
  geom_vline(xintercept = c(6, 12, 18), color = "darkred") +
  labs(
    x = " ", 
    y = "Mean response time (min)"
    ) +
   viridis::scale_color_viridis(
    name = "Season",
    discrete = TRUE) +
  theme(plot.title = element_text(size = 13),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 12),
        legend.position = "None") 
  
ggplotly(hour_eda)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Variation of Weather through the years

```{r}
map_plot = 
  ggplot() + 
  geom_polygon(data = ny_1, aes(x = long, y = lat, group = group, fill = subregion)) +
  geom_point(data = incident_zip_coor, aes(x = long, y = lat, color = mean_res_time)) +
  viridis::scale_color_viridis()

#nyc_pic = readJPEG("nyc-boroughs-map.jpg")

#map_plot = 
#  incident_zip_coor %>% 
#  ggplot(aes(x = long, y = lat, size = mean_res_time, color = mean_res_time)) +
#  annotation_custom(rasterGrob(nyc_pic, 
#                               width = unit(1,"npc"), 
#                               height = unit(1,"npc")), 
#                               -Inf, Inf, -Inf, Inf) +
#  geom_point() +
#  viridis::scale_color_viridis() + theme_set(theme_bw() + theme(legend.position = "bottom"))


#ggplotly(map_plot)
```

### Variation of response time with varying extent of snowy days

```{r}
prcp_eda =
  finaldat %>% 
  mutate(prcp_ctg = fct_relevel(prcp_ctg, c("no_prcp", "low", "high"))) %>%   group_by(date, prcp_ctg) %>% 
  summarise(mean_resp_time = mean(response_time)) %>% 
  ggplot(aes(x = prcp_ctg, y = mean_resp_time)) +
  geom_violin(aes(fill = prcp_ctg), alpha = .3) +
  stat_summary(fun.y = mean, geom = "point", size = 2, color = "blue") +
  labs(
    title = "Rainy conditions",
    y = "Mean response time(min)",
    x = " "
  ) +
  scale_x_discrete(labels = c("0(mm)", "0-25(mm)", "25(mm)+")) +
  viridis::scale_fill_viridis(
    name = "Precipitation",
    discrete = TRUE) +
  theme(plot.title = element_text(size = 12),
        axis.title.y = element_text(size = 8),
        axis.text.x = element_text(size = 9),
        legend.position = "None") 

snow_eda =
  finaldat %>% 
  mutate(snow_ctg = fct_relevel(snow_ctg, c("no_snow", "low", "high"))) %>%   group_by(date, snow_ctg) %>% 
  summarise(mean_resp_time = mean(response_time)) %>% 
  ggplot(aes(x = snow_ctg, y = mean_resp_time)) +
  geom_violin(aes(fill = snow_ctg), alpha = .3) +
  stat_summary(fun.y = mean, geom = "point", size = 2, color = "blue") +
  labs(
    title = "Snowy conditions",
    y = "Mean response time(min)",
    x = " "
  ) +
  scale_x_discrete(labels = c("0(mm)", "0-50(mm)", "50(mm)+")) +
  viridis::scale_fill_viridis(
    name = "Snow",
    discrete = TRUE) +
  theme(plot.title = element_text(size = 12),
        axis.title.y = element_text(size = 9),
        axis.text.x = element_text(size = 8),
        legend.position = "None") 

prcp_snow = prcp_eda + snow_eda 

ggplotly(prcp_snow)
```

