---
title: "Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny

---


```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(shiny)
library(tidyverse)
library(lubridate)
library(patchwork)
library(xml2)
library(rvest)
library(viridis)
library(grid)
library(rvest)

load('data/finaldat.RData')

finaldat_8min =
  finaldat %>% 
  mutate(over_8min = ifelse(response_time > 8, "8min+", "8min-"), over_8min = as.factor(over_8min))

zip_coor = read.csv("./data/US Zip Codes from 2013 Government Data")

zip_coor =
  zip_coor %>% 
  janitor::clean_names() %>% 
  rename(zip_code = zip, long = lng)
  
finaldat_8min_zip_coor = merge(finaldat_8min, zip_coor) %>%
  separate(borough_desc, into = c("remove", "borough"), sep = "-") %>%
  select(-c(remove))


```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boros = finaldat_8min_zip_coor %>% distinct(borough) %>% pull() 
# selectInput widget
selectInput("borough_choice", label = h3("Select boro"),
            choices = boros, selected = "Manhattan")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({ 
  finaldat_8min_zip_coor %>%
    filter(borough == input$borough_choice) %>%
    group_by(zip_code) %>%
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~over_8min)
  
})
```


