---
title: "Statistical analysis"
author: "Youn Kyeong Chang (uni# yc3242)"
date: "November 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)

theme_set(theme_bw())
```

```{r finaldata, include = FALSE}
load('data/finaldat.RData')

finaldat = 
  finaldat %>%
  mutate(season = 
           ifelse(incident_month %in% 9:11, "Fall",
           ifelse(incident_month %in% c(12,1,2), "Winter",
           ifelse(incident_month %in% 3:5, "Spring", "Summer"))), 
         hour_of_day = 
           ifelse(hour %in% 6:11, "morning",
           ifelse(hour %in% 12:17, "afternoon",
           ifelse(hour %in% 18:23, "night","dawn"))), 
         over_8min = ifelse(response_time > 8, "8min+", "8min-"),
         prcp_ctg = 
           if_else(prcp == 0, "no_prcp",
           if_else((prcp > 0 & prcp <= 25), "low", "high")),
         snow_ctg = 
           if_else(snow == 0, "no_snow",
           if_else((snow > 0 & snow <= 50), "low", "high")),
         over_8min = fct_relevel(over_8min, "8min-")) %>% 
  select(-over_5min)
```

## Logistic regression with binary outcome 8min- / 8min+
```{r}
finaldat = 
  finaldat %>% 
  mutate(prcp_ctg = fct_relevel(prcp_ctg, "no_prcp"),
         snow_ctg = fct_relevel(snow_ctg, "no_snow"),
         season = fct_relevel(season, "Spring"),
         hour_of_day = fct_relevel(hour_of_day, "night"))

fit_logistic =
  glm(over_8min ~ season + hour_of_day + snow_ctg + prcp_ctg, 
      family = binomial(), data = finaldat)

summary(fit_logistic)


OR_total = 
fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         lower_CI_OR = exp(estimate - 1.96*std.error),
         upper_CI_OR = exp(estimate + 1.96*std.error)) %>% 
  select(term, OR, lower_CI_OR, upper_CI_OR) %>% 
  mutate(term = fct_reorder(term, OR)) %>% 
  ggplot(aes(x = term, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = lower_CI_OR, ymax = upper_CI_OR)) +
  labs(
    x = " ",
    y = "Odds Ratio"
  ) +
  coord_flip() +
  geom_hline(yintercept = 1.0, color = "blue") +
  theme_bw()

OR_total_df = 
fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         lower_CI_OR = exp(estimate - 1.96*std.error),
         upper_CI_OR = exp(estimate + 1.96*std.error)) %>% 
  select(term, OR, lower_CI_OR, upper_CI_OR) %>%
  as.tibble() %>% 
  mutate(ctg = c("intercept", 
                 "Season", "Season", "Season", 
                 "Hour of the day", "Hour of the day", "Hour of the day",
                 "Snow", "Snow",
                 "Rain", "Rain"),
         sub_ctg_chr = c("intercept",
                     "Fall", "Summer", "Winter",
                     "Afternoon", "Dawn", "Morning",
                     "50(mm)+", "0-50(mm)",
                     "25(mm)+", "0-25(mm)"),
         sub_ctg = c("1", "2", "1", "3", "8", "6", "7", "5", "4", "5", "4")) %>%   filter(ctg != "intercept")  
  
adj = .2 # This is used in position_nudge to move the dots

ggplot(OR_total_df, aes(x = OR, y = ctg, color = sub_ctg)) +
  geom_vline(aes(xintercept = 1), size = .25, linetype = "dashed") +
  geom_errorbarh(data = filter(OR_total_df, sub_ctg == "1"), 
                 aes(xmax = upper_CI_OR, xmin = lower_CI_OR), 
                 size = .5, height = .1, 
                 color = "gray50", 
                 position = position_nudge(y = adj)) +
  geom_point(data = filter(OR_total_df, sub_ctg == "1"), 
             size = 4, color = "steelblue1",
             position = position_nudge(y = adj)) +
  geom_errorbarh(data = filter(OR_total_df, sub_ctg == "2"), 
                 aes(xmax = upper_CI_OR, xmin = lower_CI_OR), 
                 size = .5, height = .1, 
                 color = "gray50") +
  geom_point(data = filter(OR_total_df, sub_ctg == "2"), 
             size = 4, color = "gray") +
  geom_errorbarh(data = filter(OR_total_df, sub_ctg == "3"), 
                 aes(xmax = upper_CI_OR, xmin = lower_CI_OR), 
                 size = .5, height = .1, 
                 color = "gray50", position = position_nudge(y = -adj)) +
  geom_point(data = filter(OR_total_df, sub_ctg == "3"), size = 4, 
             position = position_nudge(y = -adj)) +
  geom_errorbarh(data = filter(OR_total_df, sub_ctg == "4"), 
                 aes(xmax = upper_CI_OR, xmin = lower_CI_OR), 
                 size = .5, height = .1, 
                 color = "gray50", position = position_nudge(y = +adj)) +
  geom_point(data = filter(OR_total_df, sub_ctg == "4"), 
             size = 4, color = "skyblue",
             position = position_nudge(y = +adj)) +
  geom_errorbarh(data = filter(OR_total_df, sub_ctg == "5"), 
                 aes(xmax = upper_CI_OR, xmin = lower_CI_OR), 
                 size = .5, height = .1, 
                 color = "gray50", position = position_nudge(y = -adj)) +
  geom_point(data = filter(OR_total_df, sub_ctg == "5"), 
             size = 4, color = "skyblue4", 
             position = position_nudge(y = -adj)) +
  geom_errorbarh(data = filter(OR_total_df, sub_ctg == "6"), 
                 aes(xmax = upper_CI_OR, xmin = lower_CI_OR), 
                 size = .5, height = .1, 
                 color = "gray50", 
                 position = position_nudge(y = adj)) +
  geom_point(data = filter(OR_total_df, sub_ctg == "6"), 
             size = 4, color = "steelblue1",
             position = position_nudge(y = adj)) +
  geom_errorbarh(data = filter(OR_total_df, sub_ctg == "7"), 
                 aes(xmax = upper_CI_OR, xmin = lower_CI_OR), 
                 size = .5, height = .1, 
                 color = "gray50") +
  geom_point(data = filter(OR_total_df, sub_ctg == "7"), 
             size = 4, color = "gray") +
   geom_errorbarh(data = filter(OR_total_df, sub_ctg == "8"), 
                 aes(xmax = upper_CI_OR, xmin = lower_CI_OR), 
                 size = .5, height = .1, 
                 color = "gray50", position = position_nudge(y = -adj)) +
  geom_point(data = filter(OR_total_df, sub_ctg == "8"), size = 4, 
             position = position_nudge(y = -adj)) +
  scale_x_continuous(breaks = seq(0,7,1)) +
  scale_y_discrete(limits = c("Rain", "Snow", "Season", "Hour of the day")) +
  theme_bw() +
  theme(panel.grid.minor = element_blank())

OR_hour_of_day =
fit_logistic %>% 
  broom::tidy() %>% 
  filter(str_detect(term, "hour_of_day")) %>% 
  mutate(OR = exp(estimate),
         lower_CI_OR = exp(estimate - 1.96*std.error),
         upper_CI_OR = exp(estimate + 1.96*std.error)) %>% 
  select(term, OR, lower_CI_OR, upper_CI_OR) %>% 
  mutate(term = fct_reorder(term, OR)) %>% 
  ggplot(aes(x = term, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = lower_CI_OR, ymax = upper_CI_OR), 
                color = "darkred") +
  labs(
    x = " ",
    y = " ",
    subtitle = "Hour of the day",
    caption = "reference to night"
  ) +
  coord_flip() +
  geom_hline(yintercept = 1.0, color = "blue") +
  theme_bw()

OR_prcp = 
fit_logistic %>% 
  broom::tidy() %>% 
  filter(str_detect(term, "prcp_ctg")) %>% 
  mutate(OR = exp(estimate),
         lower_CI_OR = exp(estimate - 1.96*std.error),
         upper_CI_OR = exp(estimate + 1.96*std.error)) %>% 
  select(term, OR, lower_CI_OR, upper_CI_OR) %>% 
  mutate(term = fct_reorder(term, OR)) %>% 
  ggplot(aes(x = term, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = lower_CI_OR, ymax = upper_CI_OR), 
                color = "darkred") +
  labs(
    x = " ",
    y = " "
  ) +
  coord_flip() +
  geom_hline(yintercept = 1.0, color = "blue") +
  theme_bw() 


OR_snow =
fit_logistic %>% 
  broom::tidy() %>% 
  filter(str_detect(term, "snow_ctg")) %>% 
  mutate(OR = exp(estimate),
         lower_CI_OR = exp(estimate - 1.96*std.error),
         upper_CI_OR = exp(estimate + 1.96*std.error)) %>% 
  select(term, OR, lower_CI_OR, upper_CI_OR) %>% 
  mutate(term = fct_reorder(term, OR)) %>% 
  ggplot(aes(x = term, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = lower_CI_OR, ymax = upper_CI_OR), 
                color = "darkred") +
  labs(
    x = " ",
    y = " "
  ) +
  coord_flip() +
  geom_hline(yintercept = 1.0, color = "blue") +
  theme_bw()


OR_season =
fit_logistic %>% 
  broom::tidy() %>% 
  filter(str_detect(term, "season")) %>% 
  mutate(OR = exp(estimate),
         lower_CI_OR = exp(estimate - 1.96*std.error),
         upper_CI_OR = exp(estimate + 1.96*std.error)) %>% 
  select(term, OR, lower_CI_OR, upper_CI_OR) %>% 
  mutate(term = fct_reorder(term, OR)) %>% 
  ggplot(aes(x = term, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = lower_CI_OR, ymax = upper_CI_OR), 
                color = "darkred") +
  labs(
    x = " ",
    y = " "
  ) +
  coord_flip() +
  geom_hline(yintercept = 1.0, color = "blue") +
  theme_bw()
```