---
title: "Subset analysis"
author: ""
date: "December 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
library(magick)
library(broom)

knitr::opts_chunk$set(echo = TRUE)

theme_set(theme_bw())
```

```{r finaldata, include = FALSE}
load('data/subset_dat.RData') 

subset <- dat_subset %>% 
  #Only retain variables of interest
  select(response_time, neighborhood, season:street_closed) %>% 
  #recode neightborhood (washington as opposed to Inwood + washington heights)
  mutate(neighborhood = ifelse(neighborhood == 'Inwood and Washington Heights',
      'Washington Heights', neighborhood)) %>% 
  mutate(prcp_ctg = fct_relevel(prcp_ctg, "no_prcp"),
         snow_ctg = fct_relevel(snow_ctg, "no_snow"),
         season = fct_relevel(season, "Spring"),
         hour_of_day = fct_relevel(hour_of_day, "night"))
```

## Logistic regression with among UWS
```{r}
uws_dat <- subset %>% filter(neighborhood == 'Upper West Side')
fit_logistic_uws =
  glm(over_8min ~ season + hour_of_day + snow_ctg + prcp_ctg + street_closed, 
      family = binomial(), data = uws_dat)

summary(fit_logistic_uws)
```

## Logistic regression with among Washington heights
```{r}
wash_dat <- subset %>% filter(neighborhood == 'Washington Heights')

fit_logistic_wash =
  glm(over_8min ~ season + hour_of_day + snow_ctg + prcp_ctg + street_closed, 
      family = binomial(), data = wash_dat)

summary(fit_logistic_wash)
```


```{r}
#Prepare table for visualization
table_results_uws <-  fit_logistic_uws %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>%
  bind_cols(.,  exp(confint_tidy(fit_logistic_uws))) %>% 
  select(term, OR, conf.low, conf.high) %>% 
  filter(term != '(Intercept)') %>% 
  mutate(term = c("Fall", "Summer", "Winter", "Afternoon", "Dawn", "Morning", "snow 50+", "snow 50-", "prcp 25+", "prcp 25-", "Street closed"),
         neightborhood = 'UWS') 
table_results_uws %>% 
  knitr::kable(digits = 3, "html") %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r}
table_results_wash <-  fit_logistic_wash %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>%
  bind_cols(.,  exp(confint_tidy(fit_logistic_uws))) %>% 
  select(term, OR, conf.low, conf.high) %>% 
  filter(term != '(Intercept)') %>% 
  mutate(term = c("Fall", "Summer", "Winter", "Afternoon", "Dawn", "Morning", "snow 50+", "snow 50-", "prcp 25+", "prcp 25-", "Street closed"),
         neightborhood = 'Washington Heights') 
table_results_wash %>% 
  knitr::kable(digits = 3, "html") %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
```


```{r plot_OR}
OR_UWS =
ggplot(table_results_uws, aes(x = term, y = OR)) +
  geom_hline(aes(yintercept = 1), size = 1, linetype = "dashed") +
     geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
  coord_flip()

OR_WASH =
ggplot(table_results_wash, aes(x = term, y = OR)) +
  geom_hline(aes(yintercept = 1), size = 1, linetype = "dashed") +
     geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
  coord_flip()
  
OR_all <- 
  table_results_uws %>% bind_rows(table_results_wash) %>% 
  ggplot(., aes(x = term, y = OR, colour = neightborhood)) +
  geom_hline(aes(yintercept = 1), size = 1, linetype = "dashed") +
     geom_pointrange(aes(ymin = conf.low, ymax = conf.high), 
     position = position_dodge(width = 0.30)) +
     coord_flip() + xlab('') + ylab('Odds ratio') 
ggsave("OR_all.png", plot = OR_all, width = 45, height = 25, units = "cm")
```




```




<!-- ## CombinedC -->
```{r}
# fit_logistic =
#   glm(over_8min ~ season + hour_of_day + snow_ctg + prcp_ctg + street_closed + neighborhood, 
#       family = binomial(), data = subset)
# 
# summary(fit_logistic)
# neightborhood effect is not sig

```

